### PR TITLE
deps: Be less specific for JamesIves/github-pages-deploy-action

### PR DESCRIPTION
**Pull request by ChristianTackeGSI**
See discussion here: https://github.com/FairRootGroup/FairCMakeModules/pull/38#discussion_r1623275685

### CODE REVIEW

**Review by dennisklein — APPROVED** [review]

**Comment by dennisklein** [comment]
Hm, looks like it can only understand tags.

**Comment by dennisklein** [comment]
Just remove the version completely

**Comment by dennisklein** [comment]
https://github.com/FairRootGroup/FairCMakeModules/actions/runs/9337621805/job/25699724222

**Comment by ChristianTackeGSI** [comment]
Looks like the author suggests a `@v4`?

https://github.com/jamesives/github-pages-deploy-action?tab=readme-ov-file#getting-started-airplane

Let's try that?

**Comment by dennisklein** [comment]
sure, there is a v4 tag

**Comment by dennisklein** [comment]
Lets hope its updated as we expect

**Comment by ChristianTackeGSI** [comment]
> Lets hope its updated as we expect

Yes, hopefully…

**Pull request merged**
